import BecomeTeacher from "@/components/BecomeTeacher";
import Blogs from "@/components/Blogs ";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Heros from "@/components/Heros";
import NavBar from "@/components/NavBar";
import PopularCourses from "@/components/PopularCourses";
import Testimonials from "@/components/Testimonials ";
import Total from "@/components/Total";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ed -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        </link> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <Hero></Hero>
      <Total></Total>
      <PopularCourses></PopularCourses>
      <BecomeTeacher></BecomeTeacher>
      <Heros></Heros>
      <Testimonials></Testimonials>
      <Blogs></Blogs>
      <Footer></Footer>
    </div>
  );
}
